# Generated by Django 5.2.1 on 2025-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('materia', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
            ],
        ),
        migrations.RenameField(
            model_name='doacao',
            old_name='data',
            new_name='data_transacao',
        ),
        migrations.AddField(
            model_name='doacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
