# Generated by Django 5.2.1 on 2025-05-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documento_noticia_rename_data_doacao_data_transacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='imagem',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default='documentos/default.png', upload_to='documentos/'),
        ),
    ]
