# Generated by Django 5.2.1 on 2025-06-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doacao',
            new_name='Doacoes',
        ),
    ]
