# Generated by Django 5.2.1 on 2025-05-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_documento_imagem_documento_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='parceiros/')),
                ('link', models.URLField()),
                ('texto', models.TextField()),
            ],
        ),
    ]
