# Generated by Django 5.2.1 on 2025-05-26 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.projeto')),
            ],
        ),
    ]
