# Generated by Django 5.2.2 on 2025-06-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_doacao_doacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doacoes',
            new_name='Doacao',
        ),
    ]
