# Generated by Django 5.2.1 on 2025-05-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projeto_imagemprojeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('arquivo', models.FileField(upload_to='projetos/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.projeto')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.AddField(
            model_name='doacao',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='email',
            field=models.EmailField(default='exemplo@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
