# Generated by Django 5.2.1 on 2025-05-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mediaprojeto_delete_noticia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doacao',
        ),
    ]
